### ISSUE TITLE
Support additional headers for deb packages

### ISSUE THREAD

**Issue by mateiw** [uyuni-project/uyuni#1030]
According to @rpasche's mail to uyuni-devel:

> Several metadata headers are missing for Debian packages, that causes
> major issues on Debian / Ubuntu systems.
> 
> One header is the "Multi-Arch" header, that is missing. This missing
> header causes packages to be installable over and over again. "apt" does
> not correctly "get it", that this package is already the newest
> installed and suggests these packages when searching for updates all the
> time.

My initial impression is that we have to extend `spacewalk-repo-sync` to take additional headers into account when syncing each package.
Some changes to the database might also be needed in order to store these additional packages fields.

**Comment by rpasche** [comment]
That would be cool. I think there are more headers within Debian packages that are currently not stored within the DB, but that "Multi-Arch" is an important one. I needed a whole week to track this down.

Don't know when and why Debian decides to add new headers or change something.

Robert

⁣sent from my mobile device​


-------- Originale Nachricht --------
Von: Matei Albu <notifications@github.com>
Gesendet: Mon May 27 16:18:23 GMT+02:00 2019
An: uyuni-project/uyuni <uyuni@noreply.github.com>
Cc: Robert Paschedag <robert.paschedag@web.de>, Mention <mention@noreply.github.com>
Betreff: [uyuni-project/uyuni] Support additional headers for deb packages (#1030)

According to @rpasche's mail to uyuni-devel:

> Several metadata headers are missing for Debian packages, that causes
> major issues on Debian / Ubuntu systems.
> 
> One header is the "Multi-Arch" header, that is missing. This missing
> header causes packages to be installable over and over again. "apt" does
> not correctly "get it", that this package is already the newest
> installed and suggests these packages when searching for updates all the
> time.

My initial impression is that we have to extend `spacewalk-repo-sync` to take additional headers into account when syncing each package.
Some changes to the database might also be needed in order to store these additional packages fields.


-- 
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub:
https://github.com/uyuni-project/uyuni/issues/1030

**Comment by rpasche** [comment]
@mateiw I think, just starting with 1 additional header ...```Multi-Arch``` should do it in the first place. I think this DB field could be put into ```rhnpackage```. Not sure, just thinking....

I know, in my script I wrote in the mail, *all* missing headers are added.....but this script was just an enhancement. Until today, my workaround only includes adding the missing ```Multi-Arch``` header to the packages metadata and running pretty good with it.

So with this in mind, I hope, that the DB changes to store this header should be pretty small.
