### ISSUE TITLE
Ubuntu client tools from Uyuni can't be added if a SCC account is present

### ISSUE THREAD

**Issue by juliogonzalez** [uyuni-project/uyuni#1217]
```
uyuni-master-srv-2:~ # spacewalk-common-channels ubuntu-1604-*
SUSE Manager username: admin
SUSE Manager password: 
WARNING: ubuntu-16.04-pool-amd64: redstone.xmlrpc.XmlRpcFault: The channel name 'ubuntu-16.04-pool for amd64' is reserved, please enter a different name
ERROR: ubuntu-1604-amd64-main: redstone.xmlrpc.XmlRpcFault: unhandled internal exception: User 1 does not have access to channel ubuntu-16.04-pool-amd64 or the channel does not exist
```
If the server does NOT have a SCC account, then this works fine.

If the server DOES have the SCC account and the Ubuntu client tools (for example for 16.04) added and synced, then this works fine. But the problem is that then the bootstrap repository will mix packages from SCC and packages from Uyuni.

To me it seems that as soon as a SCC acount is present, something is added to the DB that prevents using the same names SCC uses (which makes sense).

FMPOV we should just change `spacewalk-common-channels.ini` to have channel names that don't conflict with SCC, but I don't know if @mateiw used the same name on purpose, or by mistake.

**Comment by cbbayburt** [comment]
I can see three possible solutions here:

1. Document the restriction that if the user has SCC subscription, then they **have to** add the Ubuntu product in order to use `common-channels` to add Ubuntu dist channels.

2. Change the base channel in .ini file to some other label than the SCC version. The drawback would be that even if they have an SCC subscription and add the Ubuntu product, `common-channels` will not attach the child channels to the existing product, but create another pool channel. (We can do this exclusively for Uyuni)

3. Check if the base channel name is "reserved" but does not exist (this happens when there is an SCC subscription but the Ubuntu product is not added yet). And in this case, add a suffix to the base channel and create it like that. `common-channels` has some code to pick a base channel from multiple options according to a logic, but this does not cover our scenario. I think it's not a good idea to implement this overnight. We should think carefully about the consequences. This would need changes in `spacewalk-common-channels` and `spacewalk-java`

**Comment by cbbayburt** [comment]
After discussing with @mcalmer, we decided this should not block the release.

After all, the user has a couple of workarounds:

A. Edit the .ini file and change the base channel label

 or

B. Add the channels manually as they see fit

**Comment by juliogonzalez** [comment]
Ok, but then this means updating the release notes as this will clearly contradict what we have at the doc.

1. With this we are basically forcing the users to use the SUSE Manager because they they will get the client tools Ubuntu for SUSE manager.
     a) First problem: They will NOT be using the Uyuni Client Tools.
     b) Second problem: If they add then the Uyuni Client Tool channels, the bootstrap creation script will grab RPMs from BOTH SUSE manager Ubuntu client tools AND Uyuni Ubuntu c lient tools.
2. `spacewalk-common-channels` is not a supported tool. We should not instruct them to use it, and it's not even documented for Ubuntu.
3. Could work.

I can think if yet another option:

4. Duplicate the channels for Ubuntu at `spacewalk-common-channels.ini`, one set for usage with SCC (the parent channel using the same name we have now), one set for usage with Uyuni using different names (for example `uyuni-` prefixed).

**Comment by juliogonzalez** [comment]
So option 4 it was.

Doc change: https://github.com/SUSE/doc-susemanager/pull/614
