### ISSUE TITLE
repo sync fedora30 did not work

### ISSUE THREAD

**Issue by skoehnen23** [uyuni-project/uyuni#1578]
hi,
i am new in Uyuni, before i used spacwalk.
In the Uyuni GUI i have added a channel and repository for fedora30, but unforunally i got an error when i try to sync.

OS: openSUSE Leap 15.2
Uyuni: 4.0.2
RepoURL: https://mirrors.fedoraproject.org/metalink?repo=fedora-30&arch=x86_64

--
/usr/bin/spacewalk-repo-sync --channel fedora30-x86_64 --type yum
16:11:13 ======================================
16:11:13 | Channel: fedora30-x86_64
16:11:13 ======================================
16:11:13 Sync of channel started.
Retrieving repository 'fedora30-x86_64' metadata .......................................................................................................................................................................................[done]
Building repository 'fedora30-x86_64' cache ...........................................................................................................................................................................................[error]
Error building the cache:
[|] Failed to cache repo (1).
Skipping repository 'fedora30-x86_64' because of the above error.
Could not refresh the repositories because of errors.
16:12:31 RepoMDError: Cannot access repository. Maybe repository GPG keys are not imported
16:12:31 Total time: 0:01:18
--

I could sync Oracle Linux 7 and CentOS 7 without problems.

Thanks for help!

**Comment by ecsclabs** [comment]
The issue is due to the taskomatic job not handling mirrors well, have a try running it manually with

"spacewalk-repo-sync -c <channel-name>", that should work with no issues.

Again, if you specify 1 mirror from the mirror list that should also eventually work. If you notice the URL it provides is the task attempting to find a repo direct, rather than check a mirror list.


https://mirrors.fedoraproject.org/mirrorlist?repo=fedora-30&arch=x86_64

This is not an issue in the current spacewalk, and taskomatic handles mirror urls fine.

**Comment by skoehnen23** [comment]
i have start the sync with cli command, with different URLs from the mirror list. same error....

mirror: http://ftp.halifax.rwth-aachen.de/fedora/linux/releases/30/Everything/x86_64/os
--
/usr/bin/spacewalk-repo-sync --channel fedora30-x86_64 --type yum
11:12:52 ======================================
11:12:52 | Channel: fedora30-x86_64
11:12:52 ======================================
11:12:52 Sync of channel started.
Retrieving repository 'fedora30-x86_64' metadata .......................................................................................................................................................................................[done]
Building repository 'fedora30-x86_64' cache ...........................................................................................................................................................................................[error]
Error building the cache:
[|] Failed to cache repo (1).
Skipping repository 'fedora30-x86_64' because of the above error.
Could not refresh the repositories because of errors.
11:13:45 RepoMDError: Cannot access repository. Maybe repository GPG keys are not imported
11:13:46 Total time: 0:00:53
--

**Comment by ethantq** [comment]
I too have this issue with just Fedora 30, Fedora 29 works the properly. Errors below when see adding channels via spacewalk-common-channels command. Having to add each channel separately is also an issue with Fedora30

`
lm3:~ # spacewalk-common-channels -a x86_64 fedora30 fedora30-updates fedora30-modular fedora30-updates-modular
SUSE Manager username: 
SUSE Manager password:
ERROR: fedora30-x86_64: redstone.xmlrpc.XmlRpcFault: url might not be empty
lm3:~ # spacewalk-common-channels -a x86_64 fedora30 fedora30-updates fedora30-modular fedora30-updates-modular
SUSE Manager username: 
SUSE Manager password:
INFO: fedora30-x86_64 exists
ERROR: fedora30-x86_64-modular: redstone.xmlrpc.XmlRpcFault: url might not be empty
lm3:~ # spacewalk-common-channels -a x86_64 fedora30 fedora30-updates fedora30-modular fedora30-updates-modular
SUSE Manager username: 
SUSE Manager password:
INFO: fedora30-x86_64 exists
WARNING: fedora30-x86_64-modular: redstone.xmlrpc.XmlRpcFault: The channel name 'Fedora 30 Modular (x86_64)' is already in use, please enter a different name
ERROR: fedora30-x86_64-updates: redstone.xmlrpc.XmlRpcFault: url might not be empty
lm3:~ # spacewalk-common-channels -a x86_64 fedora30 fedora30-updates fedora30-modular fedora30-updates-modular
SUSE Manager username: 
SUSE Manager password:
INFO: fedora30-x86_64 exists
WARNING: fedora30-x86_64-modular: redstone.xmlrpc.XmlRpcFault: The channel name 'Fedora 30 Modular (x86_64)' is already in use, please enter a different name
WARNING: fedora30-x86_64-updates: redstone.xmlrpc.XmlRpcFault: The channel name 'Fedora 30 Updates (x86_64)' is already in use, please enter a different name
ERROR: fedora30-x86_64-updates-modular: redstone.xmlrpc.XmlRpcFault: url might not be empty
`


Channels get created with no repositories. Copying and modifying repo urls from Fedora 29 for Fedora 30 resulted in Updates, Modular, and Modular updates syncing correctly. Just eh main Fedora 30 still has issues. Also using the URL I use in spacewalk 2.9 to one mirror does not work resulting in the same error as the original submitter. Error is the same if using mirrorlist url or direct url to one specific mirror. Though errors point to two different line numbers.

**Error from sync to mirrorlist url**
`
lm3:~ # spacewalk-repo-sync -c 'fedora30-x86_64'
07:33:48 ======================================
07:33:48 | Channel: fedora30-x86_64
07:33:48 ======================================
07:33:48 Sync of channel started.
Retrieving repository 'fedora30-x86_64' metadata ...........................................................................................................................................[done]
Building repository 'fedora30-x86_64' cache ...............................................................................................................................................[error]
Error building the cache:
[|] Failed to cache repo (1).
History:
 - 'repo2solv' '-o' '/var/cache/rhn/reposync/1/fedora30-x86_64/var/cache/zypp/solv/fedora30-x86_64/solv' '-X' '/var/cache/rhn/reposync/1/fedora30-x86_64/var/cache/zypp/raw/fedora30-x86_64'
/var/cache/rhn/reposync/1/fedora30-x86_64/var/cache/zypp/raw/fedora30-x86_64/repodata/5fe8d8b1ea51dfc76231dcd923581e8654b270b99f478df97e464d5a8984883e-primary.xml.zck: repo_rpmmd: Couldn't find end of Start Tag rpm:header-range
 at line 330048:42


Skipping repository 'fedora30-x86_64' because of the above error.
Could not refresh the repositories because of errors.
07:34:08 RepoMDError: Cannot access repository. Maybe repository GPG keys are not imported
Generating bootstrap repos for all available products which had changes.
Nothing to do.
07:34:08 Total time: 0:00:19
`


**Error from cogentco mirror url**
`
lm3:~ # spacewalk-repo-sync -c 'fedora30-x86_64'
07:33:07 ======================================
07:33:07 | Channel: fedora30-x86_64
07:33:07 ======================================
07:33:07 Sync of channel started.
Retrieving repository 'fedora30-x86_64' metadata ...........................................................................................................................................[done]
Building repository 'fedora30-x86_64' cache ...............................................................................................................................................[error]
Error building the cache:
[|] Failed to cache repo (1).
History:
 - 'repo2solv' '-o' '/var/cache/rhn/reposync/1/fedora30-x86_64/var/cache/zypp/solv/fedora30-x86_64/solv' '-X' '/var/cache/rhn/reposync/1/fedora30-x86_64/var/cache/zypp/raw/fedora30-x86_64'
/var/cache/rhn/reposync/1/fedora30-x86_64/var/cache/zypp/raw/fedora30-x86_64/repodata/12dfa215b6bf77bc85de5ec9d302b82fc885e0a0de9413c846b605fa58dc8f8e-primary.xml.zck: repo_rpmmd: Extra content at the end of the document
 at line 18283:53


Skipping repository 'fedora30-x86_64' because of the above error.
Could not refresh the repositories because of errors.
07:33:10 RepoMDError: Cannot access repository. Maybe repository GPG keys are not imported
Generating bootstrap repos for all available products which had changes.
Nothing to do.
07:33:10 Total time: 0:00:02
`

**Comment by ethantq** [comment]
I just realized I had not added the GPG key under Systems-> Autoinstallation -> GPG and SSL keys. This should allow the sync to happen, it is interesting that all the other child channels sync for, just not the main one. They all have gpg enabled.

**Comment by ethantq** [comment]
Adding the Fedora GPG key did not help. Fedora 30 and 31 main repos are not syncing Updates, Modular and Modular updates are.

**Comment by paususe** [comment]
@EthanB11 what version of Uyuni? Does your network require a proxy?

**Comment by EthanB11** [comment]
2020-03 No proxy, the cogentco repo I tried in Uyuni is also the same one I use in spacewalk. I figured that was the best test.

**Comment by Conan-Kudo** [comment]
This is failing because Zypper in SUSE distributions have no support for [zck-based rpm-md repos](https://fedoraproject.org/wiki/Changes/Zchunk_Metadata) currently. It can't handle the fields or switch over to something else.

**Comment by mlandres** [comment]
Not sure which fields you're talking about. If libzypp is 'old' (i.e. without any zck knowledge) it will simply download all files (.gz and .zck). The libsolv parser (repo2solv) will pick whatever it understands. The [repo](http://ftp.halifax.rwth-aachen.de/fedora/linux/releases/30/Everything/x86_64/os) works for me on SLE-12* as well as SLE-15* or TW when added with zypper. 

As 'repo2solv' picks the .zck file rather then complaining about a missing primary.gz, libsolv seems to be compiled with zchunk support. 

Can someone provide me a tarball of the downloaded metadata (/var/cache/rhn/reposync/1/fedora30-x86_64/var/cache/zypp/raw/fedora30-x86_64) and the exact libsolv-tools version used.

**Comment by Conan-Kudo** [comment]
libsolv has been compiled with zck support since Leap 15.1 in order to support it with DNF. However, libzypp only gained support for zckmd a couple of months ago. The mismatch comes from how libzypp and libsolv interact.

**Comment by mlandres** [comment]
Yes, but as I said, older libyzpp versions will simply download both gz and zck. Then the libsolv parser picks what it needs. Newer libzypp will download either gz or zck depending on what libsolv claims to support. Both does not explain the reported error when parsing the data.

According to  the error, libsolv already picked primary.xml.zck for parsing and encountered an error within the data. So either libsolvs decompressor/parser  is broken or the downloaded data.

**Comment by Conan-Kudo** [comment]
libsolv's decompressor was broken until very recently (cf. [boo#1159314](https://bugzilla.opensuse.org/1159314)). This issue only affected SUSE distributions because libsolv on SUSE doesn't use libzck, and uses an internal implementation.

**Comment by EthanB11** [comment]
libsolv-tools-0.7.10-lp151.2.10.1.x86_64

Tar gzipped file link: https://mega.nz/#!8RtwCIAI!ez8Szc88Zw2C_M2pQmHvgAyCJR2p1R9J4deWEnxhwuQ

**Comment by mlandres** [comment]
@EthanB11, the issue @Conan-Kudo mentioned is included in libsolv-tools-0.7.11. An official update is AFAIK not yet available. One could try the update in our devel branch [zypp:SLE-15-SP1-Branch](https://download.opensuse.org/repositories/zypp:/SLE-15-SP1-Branch/openSUSE_Leap_15.1_Update).

The repo however contains just the zypp stack. Updating libsolv-tools and libyzpp from there might conflict with an installed PK-backend or YAST. In this case it would be ok to install just libsolv-tools-0.7.11 from there, replacing libsolv-tools-0.7.10 and breaking the installed libzypp versions dependency (it requires libsolv-tools=0.7.10). This requirement is a safety net and not urgently needed between 0.7.10 and 0.7.11.

**Comment by EthanB11** [comment]
I forced just the libsolv-tools and Fedora 30 is syncing now. Just need to change from the mirror list to the mirror I was using in spacewalk due to timeouts with the mirror it picked, but it seems to allow the downloading of packages now.

**Comment by phibid** [comment]
Finally is there a solution regarding this ? I have this exact same error in Uyuni 2020-05 on CentOS 7 for SCLO channel:

```
2020-05-27 16:16:44,559 [DefaultQuartzScheduler_Worker-17] INFO  com.redhat.rhn.taskomatic.task.RepoSyncTask - Syncing repos for channel: CentOS 7 Sclo (x86_64)
2020-05-27 16:16:47,074 [Thread-32166] INFO  com.redhat.rhn.taskomatic.task.RepoSyncTask - 16:16:45 ======================================
16:16:45 | Channel: centos7-x86_64-sclo
16:16:45 ======================================
16:16:45 Sync of channel started.
Retrieving repository 'centos7-x86_64-sclo' metadata [.error]
16:16:46 RepoMDError: Cannot access repository. Maybe repository GPG keys are not imported
16:16:46 Total time: 0:00:01

2020-05-27 16:16:47,076 [Thread-32167] ERROR com.redhat.rhn.taskomatic.task.RepoSyncTask - Repository 'centos7-x86_64-sclo' is invalid.
[centos7-x86_64-sclo|http://mirror.centos.org/centos-7/7/sclo/x86_64?proxy=http://proxy:8080] Valid metadata not found at specified URL
History:
 - [centos7-x86_64-sclo|http://mirror.centos.org/centos-7/7/sclo/x86_64?proxy=http://proxy:8080] Repository type can't be determined.

Please check if the URIs defined for this repository are pointing to a valid repository.
Skipping repository 'centos7-x86_64-sclo' because of the above error.
Could not refresh the repositories because of errors.

2020-05-27 16:16:47,173 [DefaultQuartzScheduler_Worker-17] ERROR com.redhat.rhn.taskomatic.task.RepoSyncTask - Command '[/usr/bin/spacewalk-repo-sync, --channel, centos7-x86_64-sclo, --type, yum, --non-interactive]' exited with error code 1
```

**Comment by phibid** [comment]
Please disregard my previous comment. Issue was coming from a wrong URL used, so no relation with the initial issue.

**Comment by sbluhm** [comment]
@skoehnen23 , can this issue be closed or does the issue still exist?

**Comment by skoehnen23** [comment]
hi @sbluhm, i dont have fedora in use anymore.

**Comment by sbluhm** [comment]
I would say then close this issue and someone can revisit it if a similar issue shows up again.

**Comment by skoehnen23** [comment]
close
