### ISSUE TITLE
move pipelines to uyuni and make monolitic reo

### ISSUE THREAD

**Issue by MalloZup** [uyuni-project/uyuni#165]
I think we should move  https://github.com/SUSE/susemanager-ci pipelines inside `uyuni` repo.

 In longterm this is an architecture problem that Uyuni need to take .

Should we put all the jenkins pipelines inside a special directory of `uyuni/ci` (1 big mono repo) or should we have 2 diff repos. 

I am in favor or monolitic big repo like google does. So we have everything there. I think that is the direction. We already discussed this in a retrospective in the past and this was the shared vision more 
or less.

**Comment by srbarrios** [comment]
@juliogonzalez we might want to move this card to our Vega squad?

**Comment by juliogonzalez** [comment]
I don't really see the big benefits of having this into the Uyuni repository other than "everything in one place". If we decussed the benefits on a retrospective, the y are not explained in the card, and on the contrary I see a lot of work adapting everything.

If we want "all in one place", the repository is now called `SUSE/susemanager-ci`, if you want to move it to `uyuni/ci` (repository), I am OK with it and I think it's the way to go (no need to change jobs, as there will be links).

If so, let's redefine this card, and then (yes) let's add it to Vega.

Otherwise, let's close this card.

**Comment by srbarrios** [comment]
I have the same opinion.
Also, even if we make Uyuni testsuite public some day, through a public CI. We can still keeping this part private.
I will close it.
