### ISSUE TITLE
Long running channel-reposync task

### ISSUE THREAD

**Issue by EthanB11** [uyuni-project/uyuni#2057]
Talked with @paususe on Gitter regarding this issue.

Built new uyuni server last week with openSUSE-Leap 15.1 and Uyuni 2020-03. After adding SLES15 and SLES15 for SAP I noticed none of systems in the non-SAP channels were getting base updates. 

`{`
`  "file_|-mgrchannels_repo_|-/etc/zypp/repos.d/susemanager:channels.repo_|-managed": {`
`    "changes": {},`
`    "pchanges": {},`
`    "comment": "File /etc/zypp/repos.d/susemanager:channels.repo is in the correct state",`
`    "name": "/etc/zypp/repos.d/susemanager:channels.repo",`
`    "result": true,`
`    "__sls__": "channels",`
`    "__run_num__": 0.0,`
`    "start_time": "12:03:17.648505",`
`    "duration": 60.472,`
`    "__id__": "mgrchannels_repo"`
`  },`
`  "pkg_|-pkg_installed_|-pkg_installed_|-installed": {`
`    "name": "pkg_installed",`
`    "result": false,`
`    "changes": {},`
`    "comment": "An error was encountered while installing package(s): Zypper command failure: ``Running scope as unit: run-rfaef8c5f7c394573899e0ffb83366124.scope\nPackage 'libruby2_5-2_5=2.5.7-4.8.1' not found.\nPackage 'ruby2.5-stdlib=2.5.7-4.8.1' not found.\nPackage 'ruby2.5=2.5.7-4.8.1' not found.",`
`    "__sls__": "packages.pkginstall",`
`    "__run_num__": 1.0,`
`    "start_time": "12:03:23.074159",`
`    "duration": 8291.905,`
`    "__id__": "pkg_installed"`
`  }`
`}`

I noticed 2 long running channel-reposync tasks and tried restartin the server using systemctl restart susemanager which didn't seem to do much. I then just rebooted the server and then the patches applied correctly when scheduling through the web insterface.

**Comment by EthanB11** [comment]
Support file: https://mega.nz/#!1YknXY4C!HBKASpWCIEu7HH4siRjkTe_78IijDdybany7Qgv8Afo

**Comment by paususe** [comment]
We are looking into this

**Comment by renner** [comment]
Let's test it with 4.1 to see if it is real. In this case we will need to fix it.

**Comment by ktsamis** [comment]
Can we get a definition of done here? What needs to happen for QA? We don't understand the issue :(

**Comment by renner** [comment]
I guess we could test this with a fresh Uyuni server: add SLES15 and SLES15 for SAP channels and see if any systems "in the non-SAP channels" are getting updates. Then keep an eye on any long running reposync tasks. @EthanB11, it would be great if you could provide some more details, especially:

- Which exact channels were you using when this happened, e.g. which SP of SLES15?
- Where those channels finished syncing when you were expecting updates?
- What exactly do you mean when you say " none of systems in the non-SAP channels were getting base updates"?
- Where does the above output come from exactly?

It will be much easier to reproduce your issue the more details you provide about what you did, thanks in advance! Then @ktsamis if it can be reproduced we have a real bug, otherwise we can close this issue.

**Comment by EthanB11** [comment]
I was setting up Uyuni fresh and syncing SLES 15.1, CentOS7, CentOS8, and Ubuntu 18.04. This happened right after setting schedules and pressing sync now for the intial sync as I set up my schedules.

**Comment by ktsamis** [comment]
Can we close this? Does it work now?

**Comment by mcalmer** [comment]
no response, so let's close it
