### ISSUE TITLE
Proxy client reaching out to internet for packages

### ISSUE THREAD

**Issue by samcoddington** [uyuni-project/uyuni#2488]
# Additional Information
SLES 15.1 Client bootstrapped to proxy from the web UI is reaching out to suse.com for packages when running zypper from the command line.  Package installs from the Uyuni web UI work correctly.

## Version of Uyuni Server and Proxy (if used)
Server Version - 2020.01
Proxy Version - 4.1.1-1.1

## Details about issue
I have a Uyuni proxy located in an isolated network, firewalled off from the internet.  I bootstrapped a client to the proxy through the Uyuni web UI.   Installing packages to the client using the Uyuni web UI works.  Using 'zypper install' the client attempts to reach out to suse.com and fails.

**Comment by juliogonzalez** [comment]
First problem is that there you are on a really old version of the Server, so I would not be surprised if the bug is even fixed since then.

We'll will need to get the server updated and the proxy before having a look here.

But yes, I know there are still issues at least on US with the update. Since I didn't have reply on my ticket for the mirrors, I will try to reach someone tomorrow via chat, and hopefully you will be able to update, so we can see if this is bug still applies.

Anyway, just for the sake of my curiosity:

1. Can you share the output of `zypper lr`
2. Did you, by any chance, try to register the client with SUSEConnect after the onboarding?
3. Can you paste the bootstrap script here, removing any confidential data?

**Comment by samcoddington** [comment]
I'm working on updating the uyuni server now, but I keep running into issues.  Is there something different I need to do on SUSE Enterprise Server?  I followed the documents here and it's still showing 2020.01

https://www.uyuni-project.org/uyuni-docs/uyuni/upgrade/server-intro-uyuni.html

**Comment by juliogonzalez** [comment]
If you are in any country in the american continent, it seems the Provo mirrors that serve such countries where [having problems](https://progress.opensuse.org/issues/69334#note-17) that, hopefully, are fixed now.

So if your problems were related to package verification, give it a try again and let us now if problems are gone.

As for the instructions: you must follow are those for a [major upgrade](https://www.uyuni-project.org/uyuni-docs/uyuni/upgrade/server-major-upgrade-uyuni.html), as the base OS is changed.

I am not sure what do you mean with "is there something different I need to do on SUSE Enterprise Server?" Are you using SUSE Linux Enterprise Server as base OS for the server?

**Comment by samcoddington** [comment]
Yes, our base OS with the Uyuni server install is SLES 15.1.  The upgrade script /usr/lib/susemanager/bin/server-migrator.sh looks be be fore openSUSE only.  I did run a zypper upgrade and the /usr/lib/susemanager/bin/pg-migrate-10-to-12.sh script, but now I'm getting a 404 error on the web gui which I'm trying to debug.

**Comment by juliogonzalez** [comment]
> Yes, our base OS with the Uyuni server install is SLES 15.1.

This is an unsupported scenario. Uyuni Server and Proxy to are be installed only on top of openSUSE Leap (current stable on top of Leap 15.2)

**Comment by juliogonzalez** [comment]
Closing for now, but feel free to reopen if the problem persists after installing both the Server and the Proxy on top of Leap.
