### ISSUE TITLE
No Uyuni client repos for Oracle Linux 6 and 7

### ISSUE THREAD

**Issue by ewenf-uindy** [uyuni-project/uyuni#2591]
Openleap 15.2
Uyuni 2020.07

When setting up my server and syncing repos from spacewalk-common-channels, the Oracle Linux 6 and 7 client show no repo assigned to them.

This is met with a message stating "No repositories are currently associated with this channel."  This occurs for both the main repo as well as the development line.  The centos6 and 7 pulled rpms from their repos just fine.

**Comment by mateiw** [comment]
Could you post the sections `[oraclelinux7*]` and `[oraclelinux6*]` from your `/etc/rhn/spacewalk-common-channels.ini`?
Any related error in the logs?

**Comment by ewenf-uindy** [comment]
All 4 repos syncs say "No repositories are currently associated with this
channel".  Looking at common-channels.ini, it appears as if repo are listed.

Oracle Linux 7 Uyuni Repos

[oraclelinux7-uyuni-client]
name     = Uyuni Client Tools for %(base_channel_name)s
archs    = %(_x86_archs)s
base_channels = oraclelinux7-%(arch)s
gpgkey_url =
https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/CentOS7-Uyuni-Client-Tools/CentOS_7/repodata/repomd.xml.key
gpgkey_id = %(_uyuni_gpgkey_id)s
gpgkey_fingerprint = %(_uyuni_gpgkey_fingerprint)s
repo_url =
https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/CentOS7-Uyuni-Client-Tools/CentOS_7/

[oraclelinux7-uyuni-client-devel]
name     = Uyuni Client Tools for %(base_channel_name)s (Development)
archs    = %(_x86_archs)s
base_channels = oraclelinux7-%(arch)s
gpgkey_url =
https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Master:/CentOS7-Uyuni-Client-Tools/CentOS_7/repodata/repomd.xml.key
gpgkey_id = %(_uyuni_gpgkey_id)s
gpgkey_fingerprint = %(_uyuni_gpgkey_fingerprint)s
repo_url =
https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Master:/CentOS7-Uyuni-Client-Tools/CentOS_7/

Oracle 6 Linux Uyuni Repo

[oraclelinux6-uyuni-client]
name     = Uyuni Client Tools for %(base_channel_name)s
archs    = %(_x86_archs)s
base_channels = oraclelinux6-%(arch)s
gpgkey_url =
https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/CentOS6-Uyuni-Client-Tools/CentOS_6/repodata/repomd.xml.key
gpgkey_id = %(_uyuni_gpgkey_id)s
gpgkey_fingerprint = %(_uyuni_gpgkey_fingerprint)s
repo_url =
https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/CentOS6-Uyuni-Client-Tools/CentOS_6/

[oraclelinux6-uyuni-client-devel]
name     = Uyuni Client Tools for %(base_channel_name)s (Development)
archs    = %(_x86_archs)s
base_channels = oraclelinux6-%(arch)s
gpgkey_url =
https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Master:/CentOS6-Uyuni-Client-Tools/CentOS_6/repodata/repomd.xml.key
gpgkey_id = %(_uyuni_gpgkey_id)s
gpgkey_fingerprint = %(_uyuni_gpgkey_fingerprint)s
repo_url =
https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Master:/CentOS6-Uyuni-Client-Tools/CentOS_6/


---------------

Len Ewen

Systems Administrator 1

Information Technology

University of Indianapolis

(317) 788-3362

[image: UIndyIT.jpg]

Confidentiality Notice: This communication and/or its content are for the
sole use of the intended recipient, and may be privileged, confidential, or
otherwise protected from disclosure by law. If you are not the intended
recipient, please notify the sender and then delete all copies of it.
Unless you are the intended recipient, your use or dissemination of the
information contained in this communication may be illegal.

**Comment by juliogonzalez** [comment]
Do I correctly understand that you already had CentOS and the Uyuni client tools repositories for CentOS added by spacewalk-common-channels and synced?

Did you see any errors when adding the oracle linux channels, including the client tools?

**Comment by juliogonzalez** [comment]
Ping @ewenf-uindy

**Comment by milari** [comment]
Hi,
You say something like this?
![Cattura](https://user-images.githubusercontent.com/26594772/99939655-d946a100-2d6a-11eb-8f96-9c64cd1f7e8f.PNG)

**Comment by milari** [comment]
Please, take a look also to:
https://github.com/SUSE/doc-susemanager/issues/921
Thanks,
M.

**Comment by milari** [comment]
uyuni:/var/log/rhn/reposync # mgr-create-bootstrap-repo --with-custom-channels
1. centos-7-x86_64-uyuni
2. centos-8-x86_64-uyuni
3. openSUSE-Leap-15.2-x86_64-uyuni
4. oracle-7-x86_64-uyuni
Enter a number of a product label: 4

Creating bootstrap repo for oracle-7-x86_64-uyuni
copy 'python-jinja2-2.7.2-4.el7.noarch'
copy 'python-requests-2.6.0-10.el7.noarch'
copy 'python-setuptools-0.9.8-7.el7.noarch'
copy 'python-tornado-2.2.1-8.el7.noarch'
copy 'python-tornado-4.2.1-5.el7.x86_64'
copy 'python-backports-ssl_match_hostname-3.5.0.1-1.el7.noarch'
copy 'python-backports-1.0-8.el7.x86_64'
copy 'python-simplejson-3.2.0-1.el7.x86_64'
copy 'PyYAML-3.10-11.el7.x86_64'
copy 'python-markupsafe-0.11-10.el7.x86_64'
copy 'python-urllib3-1.10.2-7.el7.noarch'
copy 'libyaml-0.1.4-11.el7_0.i686'
copy 'libyaml-0.1.4-11.el7_0.x86_64'
copy 'python-chardet-2.2.1-3.el7.noarch'
copy 'python-six-1.9.0-2.el7.noarch'
copy 'python-babel-0.9.6-8.el7.noarch'
copy 'yum-rhn-plugin-2.0.1-10.0.1.el7.noarch'
copy 'yum-3.4.3-168.0.3.el7.noarch'
copy 'openssl-1.0.2k-19.0.1.el7:1.x86_64'
copy 'openssl-libs-1.0.2k-19.0.1.el7:1.i686'
copy 'openssl-libs-1.0.2k-19.0.1.el7:1.x86_64'
copy 'python-ipaddress-1.0.16-2.el7.noarch'
copy 'redhat-rpm-config-9.1.0-88.0.1.el7.noarch'
copy 'rpm-python-4.11.3-45.el7.x86_64'
copy 'dmidecode-3.2-5.el7:1.x86_64'
Directory walk started
Directory walk done - 25 packages
Temporary output repo path: /srv/www/htdocs/pub/repositories/oracle/7/bootstrap.tmp/.repodata/
Preparing sqlite DBs
Pool started (with 5 workers)
Pool finished
ERROR: package 'salt' not found
ERROR: package 'salt-minion' not found
ERROR: package 'python2-salt' not found
ERROR: package 'python-futures' not found
ERROR: package 'python-msgpack-python' not found
ERROR: package 'python-psutil' not found
ERROR: package 'python-pycrypto' not found
ERROR: package 'python-singledispatch' not found
ERROR: package 'python-zmq' not found
ERROR: package 'zeromq' not found
ERROR: package 'python-certifi' not found
ERROR: package 'python2-rhnlib' not found
ERROR: package 'spacewalk-check' not found
ERROR: package 'python2-spacewalk-check' not found
ERROR: package 'spacewalk-client-setup' not found
ERROR: package 'python2-spacewalk-client-setup' not found
ERROR: package 'spacewalk-client-tools' not found
ERROR: package 'python2-spacewalk-client-tools' not found
ERROR: package 'python2-uyuni-common-libs' not found
ERROR: none of 'mgr-daemon', 'spacewalksd' found
ERROR: package 'suseRegisterInfo' not found
ERROR: package 'python2-suseRegisterInfo' not found
ERROR: package 'python2-hwdata' not found

Suggestions:
mgr-create-bootstrap-repo uses the locally synchronized versions of files
from the Tools repository, and uses the locally synchronized pool channel
for dependency resolution.
Both should be fully synced before running the mgr-create-bootstrap-repo script.

uyuni:/var/log/rhn/reposync #

**Comment by juliogonzalez** [comment]
I think you just hit a problem on how spacewalk-common-channels is working. Did you get:

> redstone.xmlrpc.XmlRpcFault: There's already a defined repository with given url, please reuse it.

When you added the channels via spacewalk-common-channels?

If so, that happens because you already have the repository defned for CentOS7, as the URL is the same for RHEL, CentOS and Oracle 7.

Try to manually aisng the CentOS7 uyuni client tools repository to the Oracle 7 Client tools Channel, launch a sync, then launch mgr-bootstra-repo and let us know the outcome.

If it works, then we need a separate bug report.

**Comment by milari** [comment]
Hi,
I don't know, because in /var/log/rhn/reposync there isn't a log for oraclelinux7-uyuni-client-tools.
Sync date for centos7:
![immagine](https://user-images.githubusercontent.com/26594772/100361250-386e1500-2ffa-11eb-9453-147bd570c95b.png)

So I tried to manually add to this channel, packages of centos7 one: 
![immagine](https://user-images.githubusercontent.com/26594772/100361406-6c493a80-2ffa-11eb-9477-212e1b9a43bf.png)

Sync of repo, still fails:
![immagine](https://user-images.githubusercontent.com/26594772/100361467-79fec000-2ffa-11eb-97f5-256219127476.png)

But in this way mgr-create-bootstrap-repo works:
# mgr-create-bootstrap-repo --with-custom-channels
1. centos-7-x86_64-uyuni
2. centos-8-x86_64-uyuni
3. openSUSE-Leap-15.2-x86_64-uyuni
4. oracle-7-x86_64-uyuni
Enter a number of a product label: 4

Creating bootstrap repo for oracle-7-x86_64-uyuni
copy 'salt-3000-23.1.uyuni.x86_64'
copy 'salt-minion-3000-23.1.uyuni.x86_64'
copy 'python2-salt-3000-23.1.uyuni.x86_64'
copy 'python-futures-2.1.3-0.8.8.uyuni.x86_64'
copy 'python-jinja2-2.7.2-4.el7.noarch'
copy 'python-msgpack-python-0.4.6-2.8.uyuni.x86_64'
copy 'python-psutil-1.2.1-0.10.8.uyuni.x86_64'
copy 'python-pycrypto-2.6.1-2.8.uyuni.x86_64'
copy 'python-requests-2.6.0-10.el7.noarch'
copy 'python-setuptools-0.9.8-7.el7.noarch'
copy 'python-singledispatch-3.4.0.3-3.1.uyuni.noarch'
copy 'python-tornado-2.2.1-8.el7.noarch'
copy 'python-tornado-4.2.1-5.el7.x86_64'
copy 'python-zmq-14.5.0-3.8.uyuni.x86_64'
copy 'zeromq-4.0.5-1.8.uyuni.x86_64'
copy 'python-backports-ssl_match_hostname-3.5.0.1-1.el7.noarch'
copy 'python-backports-1.0-8.el7.x86_64'
copy 'python-certifi-2015.9.6.2-2.8.uyuni.noarch'
copy 'python-simplejson-3.3.1-2.8.uyuni.x86_64'
copy 'PyYAML-3.10-11.el7.x86_64'
copy 'python-markupsafe-0.11-10.el7.x86_64'
copy 'python-urllib3-1.10.2-7.el7.noarch'
copy 'libyaml-0.1.4-11.el7_0.i686'
copy 'libyaml-0.1.4-11.el7_0.x86_64'
copy 'python-chardet-2.2.1-3.el7.noarch'
copy 'python-six-1.9.0-2.el7.noarch'
copy 'python-babel-0.9.6-8.el7.noarch'
copy 'yum-rhn-plugin-4.2.1-2.1.uyuni.noarch'
copy 'yum-3.4.3-168.0.3.el7.noarch'
copy 'python2-rhnlib-4.2.1-2.1.uyuni.noarch'
copy 'openssl-1.0.2k-19.0.1.el7:1.x86_64'
copy 'openssl-libs-1.0.2k-19.0.1.el7:1.i686'
copy 'openssl-libs-1.0.2k-19.0.1.el7:1.x86_64'
copy 'python-ipaddress-1.0.16-2.el7.noarch'
copy 'redhat-rpm-config-9.1.0-88.0.1.el7.noarch'
copy 'rpm-python-4.11.3-45.el7.x86_64'
copy 'spacewalk-check-4.2.2-2.1.uyuni.noarch'
copy 'python2-spacewalk-check-4.2.2-2.1.uyuni.noarch'
copy 'spacewalk-client-setup-4.2.2-2.1.uyuni.noarch'
copy 'python2-spacewalk-client-setup-4.2.2-2.1.uyuni.noarch'
copy 'spacewalk-client-tools-4.2.2-2.1.uyuni.noarch'
copy 'python2-spacewalk-client-tools-4.2.2-2.1.uyuni.noarch'
copy 'python2-uyuni-common-libs-4.2.1-2.1.uyuni.x86_64'
copy 'mgr-daemon-4.2.2-2.1.uyuni.noarch'
copy 'suseRegisterInfo-4.2.1-2.1.uyuni.noarch'
copy 'python2-suseRegisterInfo-4.2.1-2.1.uyuni.noarch'
copy 'python2-hwdata-2.3.5-2.8.uyuni.noarch'
copy 'dmidecode-3.2-5.el7:1.x86_64'
Directory walk started
Directory walk done - 48 packages
Temporary output repo path: /srv/www/htdocs/pub/repositories/oracle/7/bootstrap.tmp/.repodata/
Preparing sqlite DBs
Pool started (with 5 workers)
Pool finished

**Comment by milari** [comment]
anyway, if now it's all right, why pkg management on clients, still fails?

# yum install xauth
Loaded plugins: susemanagerplugin
https://uyuni.example.it:443/rhn/manager/download/oraclelinux7-x86_64/repodata/repomd.xml: [Errno 14] curl#22 - "The requested URL returned error: 503"
Trying other mirror.


 One of the configured repositories failed (Oracle Linux 7 (x86_64)),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=susemanager:oraclelinux7-x86_64 ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable susemanager:oraclelinux7-x86_64
        or
            subscription-manager repos --disable=susemanager:oraclelinux7-x86_64

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=susemanager:oraclelinux7-x86_64.skip_if_unavailable=true

failure: repodata/repomd.xml from susemanager:oraclelinux7-x86_64: [Errno 256] No more mirrors to try.
https://uyuni.example.it:443/rhn/manager/download/oraclelinux7-x86_64/repodata/repomd.xml: [Errno 14] curl#22 - "The requested URL returned error: 503"

**Comment by milari** [comment]
And if I try to bootstrap any system, also yet added to systems list, I always receive message:
 Error during applying the bootstrap state, message: Salt user does not have sufficient permissions
Thanks,
M.

**Comment by juliogonzalez** [comment]
Sorry, but we need to go back some steps. We are mixing issues here.

First of all, clean the Oracle7 client tools channel. You don't need to add any packages manually as you did.

Then you add the CentOS7 client tools repository to the Oracle7 client tools channel. I don't see that on any of the screenshots above. The closest one is:
![image](https://user-images.githubusercontent.com/4226070/100558723-d2121c80-32af-11eb-99e2-9f1fdeae6734.png)
But it seems the CentOS7 repository was not attached.

**Comment by milari** [comment]
Hi,
not sure to have undrestand correctly your request... but I'll try to explain/resume here experienced issues.

I have added channel centos 7; added channel oraclelinux7; when syncing channel, the oracle tools client of latest one (oracle) fails with message You correctly reported before and that's the main theme of this issue.

Later, I've copied manually centos 7 packages in oracle linux 7 client tool one, because You said are the same; in this way mgr-create-bootstrap-repo worked; I've also reported that Web UI of bootstrap fails and only way of attach clients is by script.

Moreover, may be You're right when saying may be I find other issues: all clients added "behind" a proxy doesn't work correctly with repos.

Please let me know if I resumed correctly.
Thanks.

**Comment by juliogonzalez** [comment]
First question: are you managing both CentOS7 and Oracle7?

Assuming that the answer is yes: If you manage both CentOS7 and Oracle7 and enable all channels for CentOS7 first, then `spacewalk-common-channels` will complain when you add Oracle 7 as the Oracle 7 client tools can create a repository with the same URL that is used by CentOS7 client tools. You should get an error about that. I assume that was the case.

As a result, on the WebUI you will see an Oracle 7 Client tools channel, with no repository assigned (what you showed on a screenshot) The fix to that to adding the CentOS7 client tools repository to the Oracle 7 Client tools channel (please notice the difference between channel and repository). Then launch a resync of the Oracle 7 client tools channel, and then the bootstrap creation should work fine.

No copying of packages is needed.

**Comment by milari** [comment]
Hi,
honestly I don't understand the point.
Anyway:
- removed packages from oracle 7 uyuni client tools
Now channel list is this one (no packages in latest raw):
![immagine](https://user-images.githubusercontent.com/26594772/100616482-70869800-3319-11eb-9518-a414b564cdf7.png)
Now going to the repo of last channel, try to sync and again:
![immagine](https://user-images.githubusercontent.com/26594772/100616604-9f9d0980-3319-11eb-9e58-41fac1a31d98.png)
So now what?
thanks.

**Comment by juliogonzalez** [comment]
Go to "add/remove", and add the CentOS7 client tools repository to that channel.

Then, even with a sync, the packages from the CentOS7 client tools repository  should become available for `Uyuni Client Tools for Oracle Linux 7 (x86_64)` channel. If not, force a reposync.

In the end you will have one repository for the CentOS7 client tools, assigned to to channels (one is the client tools for CentOS7, the other the client tools for Oracle 7).

After that, `mgr-create-bootstrap` should start working.

**Comment by milari** [comment]
Hi,
sorry to say that something still missing, imho... let me try to explain:
![immagine](https://user-images.githubusercontent.com/26594772/100636762-55745200-3332-11eb-8767-deea818bb848.png)

In upper suggested channel, I've added the other one:
![immagine](https://user-images.githubusercontent.com/26594772/100636807-691fb880-3332-11eb-8307-02401a4d60b2.png)

forced resync of oracle 7 repo and then checked in channels, but still "0" packages reported:
![immagine](https://user-images.githubusercontent.com/26594772/100637045-b2700800-3332-11eb-8b40-00285272c386.png)

so forced as You suggested sync, but again:
![immagine](https://user-images.githubusercontent.com/26594772/100637138-d2073080-3332-11eb-9196-2c32f2b3d40a.png)

Let me know if I understand correctly your suggestions.
Thanks.

**Comment by juliogonzalez** [comment]
Add the Uyuni Client tools for CentOS7 **repository** to the Uyuni CLient Tools for Oracle Linux **channel**

On your screenshot you are adding the repository to the wrong channel (Oracle Linux 7)

**Comment by milari** [comment]
Hi.
Thanks, latest instructions worked!
Let me do some tests... in the meanwhile, would You please suggest me how address other problem discovered previously (all clients added "behind" a proxy seem doesn't work correctly with repos)?

**Comment by juliogonzalez** [comment]
Glad it worked! :-)

Still what I gave you is a workaround. We already have an internal card to fix this, and I asked our team to give some priority to it, so this can be done transparently with `spacewalk-common-channels`.

As for your other issue with clients and proxy, please create a new GitHub issue for it, so we can track the research (and potential fix) separately.

**Comment by milari** [comment]
Hi,
I'd like to know if for the same reason reported above, is impossible to create a Distribution Channel Map for oracle linux if Centos one yet exist.
Thanks a lot.
![immagine](https://user-images.githubusercontent.com/26594772/102252209-19321b80-3f06-11eb-9c69-9cba6d7b57b9.png)

**Comment by juliogonzalez** [comment]
@mcalmer I seem to remember you fixed the problem of having about creating two repos with the same URL, that prevented adding CentOS and Oralce at the  same time?

If so, I think we can close this card, and @milari can open a new bug about this last problem.

**Comment by mcalmer** [comment]
> @mcalmer I seem to remember you fixed the problem of having about creating two repos with the same URL, that prevented adding CentOS and Oralce at the same time?

Yes, this should be fixed in spacewalk-common-channels

**Comment by juliogonzalez** [comment]
Closing then.

@milari, please update to 2021.02 and check again. Reopen the bug if adding the channels still doesn't work.

As for the problem reported at https://github.com/uyuni-project/uyuni/issues/2591#issuecomment-745456326, check if it's fixed as well. If it's not, create a *new* bug.

Thanks!
