### ISSUE TITLE
Uyuni Question - Uyuni 2021.06 on SLES 15.3

### ISSUE THREAD

**Issue by t-ru** [uyuni-project/uyuni#3927]
Hello,

openSUSE Leap 15.3 and SLES 15.3 are binary compatible. 

Is it now possible to install Uyuni Server on SLES 15.3 or SLES4SAP 15.3 instead on Leap 15.3?

Best regards
Thomas

**Comment by Shirocco88** [comment]
uyuni server is only supported on openSUSE Leap 15.3

**Comment by juliogonzalez** [comment]
@t-ru while they are binary compatible, there are still some differences:

- SLE has modules, while openSUSE does not have them
- Consequently the repositories are specific for each OS, as @Shirocco88 correctly pointed out, and AFAIK Leap still contains more packages than those shipped by SLE.

And from the Uyuni POV, we only develop for openSUSE Leap 15.3 as base OS, as @Shirocco88 pointed out.

So while you can try to overcome the problems, it's not supported at all.

Since the question is now replied, I am closing this issue.
