### ISSUE TITLE
Problems with the SSL during Uyuni setup 

### ISSUE THREAD

**Issue by RR-RD** [uyuni-project/uyuni#4990]
# Problem description

I'm trying to setup Uyuni on OpenSuse 15.3, I'm able to successfully go through the first installation steps, however the installation fails on the SSL issue part

## Version of Uyuni Server and Proxy (if used)

The setup downloads the latest stable version available 

## Details about the issue

Installation fails on generating the self-signed certificate with Exit value: 1.  This [LINK](https://imgur.com/a/GioA4mF) shows the information contained on the rhn_installation.log

**Comment by reedacus25** [comment]
Just chiming in to say that I too have this issue.

Given the error:
```
ERROR: Certificate 'C = FO, ST = 0B, L = AR, O = FOO, OU = BAR, CN = BAZ.FQDN' not yet valid
```
I wonder if this is some kind of race condition where openssl is generating the cert "too quickly"?

**Comment by mcalmer** [comment]
Is " Country FO" a real country 2 letter code? At least  this is limited by openssl to special values.
Try DE or US or another valid value.

**Comment by RR-RD** [comment]
Mine is using US for  the country code, but either way fails. I've tried the default DE, same results.

**Comment by reedacus25** [comment]
> Is " Country FO" a real country 2 letter code? At least this is limited by openssl to special values.
> Try DE or US or another valid value.

My actual usage used US.

**Comment by spartonicus** [comment]
This issue must have been introduced lately.  Installed a test system two weeks prior with no problems.  Built two new servers to test and ran into the SSL issue described here.  Contents of SSL seems to not matter.

**Comment by reedacus25** [comment]
I tried starting over on a clean install with the "master" branch repo (`repo=${repo}Uyuni:/Master/images/repo/Uyuni-Server-POOL-x86_64-Media1/`), which codifies as `2022.03-1.1.uyuni1`, and no luck with that either.

However, if I specify the 22.01 branch repo (`repo=${repo}Uyuni:/Snapshots:/2022.01/images/repo/Uyuni-Server-POOL-x86_64-Media1/`), it works.

So it doesn't appear to be an issue with 15.3 explicitly, it appears to be something that changed between `22.01` and `22.02`, and hasn't been fixed in `master/22.03`.

**Comment by dvosburg** [comment]
This appears to have something to do with the fact that daylight savings started in the US a week earlier.

If you use DE as your country and set the system to be in CET, this issue does not appear.

**Comment by mcalmer** [comment]
Thanks for the report. It has nothing to do with DST, but with timezones :-)
Next Uyuni version will have the fix

**Comment by juliogonzalez** [comment]
@RR-RD that repository is not to be used. It's just a snapshot of 2022.01 in case we need to reproduce issues, for example for migrations from 2022.01 directly in to the last Uyuni version.

The fix https://github.com/uyuni-project/uyuni/pull/5013 will be included into 2022.03

Until that moment, I am not sure if @mcalmer can provide a workaround.

One option would be overwriting `mgr_ssl_cert_setup.py` at the system (can't recall the full path, but you can use 
`find` to find it, with https://github.com/mcalmer/uyuni/blob/8ed03acfdb53d303da3e2554f91093e7b4eac0f7/spacewalk/certs-tools/mgr_ssl_cert_setup.py

**Comment by mcalmer** [comment]
@RR-RD please check the Pull Request linked by @juliogonzalez .
The fix is really only to change `now = datetime.now()` into `now = datetime.utcnow()` in mgr_ssl_cert_setup.py.
You can just make the change in the installed system. You can find the file at 
`/usr/lib/python3.6/site-packages/certs/mgr_ssl_cert_setup.py`

**Comment by RR-RD** [comment]
@mcalmer Thanks, that change did the trick. I was able to pass the error message and complete the installation.

**Comment by mcalmer** [comment]
thanks for verifying
