### ISSUE TITLE
RHEL8 parent channels not found when creating bootstrap repo

### ISSUE THREAD

**Issue by sleepygh0st** [uyuni-project/uyuni#5150]
# Problem description
Unable to create RHEL8-x86_64 bootstrap repos, 'rhel8-x86_64' not found in existing parent channel options '[]'

## Version of Uyuni Server 

Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2022.03-172.4.uyuni1
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2022.03-172.4.uyuni1.src
Summary        : Uyuni Server

## Details about the issue

After syncing official RHEL8 repos into Uyuni using base channel name (or any other variation of the base channel name, including rhel8-pool-x86_64) and attempting to create the bootstrap repo, the following error occurs:

mgr-create-bootstrap-repo --debug -n --with-custom-channels --with-parent-channel rhel8-x86_64 -c RHEL8-x86_64
'rhel8-x86_64' not found in existing parent channel options '[]'

Looking into the database, the parent channel is in fact listed:

 # psql -U uyuni -d uyuni -c 'select label from rhnChannel where parent_channel IS null and org_id IS NOT NULL'
Password for user uyuni:
             label
-------------------------------
 rhel8-x86_64
 centos7-x86_64
 ubuntu-20.04-pool-amd64-uyuni
 rhel7-base-uyuni
 rockylinux8-x86_64
(5 rows)

**Comment by sleepygh0st** [comment]
After further RTFM, I was able to work around this issue by replacing the RHEL8 definition in /usr/share/susemanager/mgr_bootstrap_data.py with a definition such as:

    'RHEL8-x86_64' : {
        'BASECHANNEL' : 'rhel8-base-uyuni', 'PKGLIST' : RES8 + RES8_X86,
        'DEST' : '/pub/repositories/res/8/bootstrap/'
     },

**Comment by MaxHerrmannSVA** [comment]
Greeting,

im not sure if this Bugreport should be closed.
I had the same issue and it could only be fixed with your solution.

Here's my Version Info:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2022.03-172.4.uyuni1
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : out-of-date (version 2022.02-171.1.uyuni1 installed)
Source package : Uyuni-Server-release-2022.03-172.4.uyuni1.src
Summary        : Uyuni Server

I just copied mgr_bootstrap_data.py to mgr_bootstrap_data-rhel7_custom.py and worked with "mgr-create-bootstrap-repo --datamodule=mgr_bootstrap_data-rhel7_custom" so that the original file stays untouched.
