### ISSUE TITLE
After upgrade to 2022.12 rhn_web_ui.log showing 'org.postgresql.util.PSQLException: ERROR: column "physical" does not exist'

### ISSUE THREAD

**Issue by gabjef** [uyuni-project/uyuni#6511]
### Problem description

Uyuni throwing the error 'org.postgresql.util.PSQLException: ERROR: column "physical" does not exist' after upgrade from 2022.06 tp 2022.12

### Steps to reproduce

1.Do operations with the Web UI
2.
3.
...

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2022.11-220400.195.1.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2022.11-220400.195.1.uyuni2.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

### Uyuni proxy version (if used)

```bash
N/A
```

### Useful logs

```bash
Attached rhn_web_ui.log and schema-from-20230104-140555-to-susemanager-schema-4.4.3.log
```

**Comment by gabjef** [comment]
[rhn_web_ui.log](https://github.com/uyuni-project/uyuni/files/10469210/rhn_web_ui.log)
[schema-from-20230104-140555-to-susemanager-schema-4.4.3.log](https://github.com/uyuni-project/uyuni/files/10469212/schema-from-20230104-140555-to-susemanager-schema-4.4.3.log)

**Comment by gabjef** [comment]
After the 2022.12 upgrade we are seeing other odd behavior with Uyuni, such as:
- Deleted minions still showing up via `spacewalk-report inventory` command
- Newly onboarded minions "swiping " the UUID of an existing minion during a "Hardware List Refresh" task
I will wait on reporting those pending the response to this issue.
Thanks.

**Comment by mcalmer** [comment]
The problem with "physical" is already known and will be fixed in the next version.

About spacewalk-report: it uses the report DB. The data of the report DB are refreshed once per day. So it is normal that you still see systems or data in the report when you just changed it and check the inventory. Please check a day later or refresh the data by triggering the taskomatic job via the Web UI:

  Admin => Task Schedules => mgr-update-reporting-bunch => Single Run Schedule

Alternative you can use the "legacy" mode of spacewalk-report. `spacewalk-report --legacy-report inventory`
