### ISSUE TITLE
Salt module pkg.mod_repo breaks /etc/apt/sources.list

### ISSUE THREAD

**Issue by phibid** [uyuni-project/uyuni#6801]
### Problem description

Not sure exactly which OS are affected, but in my case this was noticed for Debian 11, so I suppose that Ubuntu OS may be affected too, but needs confirmation.

While applying the highstate on a Debian 11 server with several external repositories configured, `sources.list` is populated with the external repo content, however not correctly formatted.

Example. Original state, we have nodeje external repository configured and sources.list is empty:

```
root@uyuni05v : /etc/apt/sources.list.d # cat nodesource.list
deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_15.x bullseye main
deb-src [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_15.x bullseye main
root@uyuni05v : /etc/apt # ls -l sources.list
-rw-r--r-- 1 root root 0 Mar 30 10:50 sources.list
```

I now apply the highstate on this server. `nodesource.list` remains untouched but its content has been copied in `/etc/apt/sources.list` with no newline, which actually breaks apt:

```
root@uyuni05v : /etc/apt # cat sources.list
deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_15.x bullseye maindeb-src [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_15.x bullseye mainroot@uyuni05v : /etc/ap
```

The highstate log:

```
----------
          ID: disable_repo_0
    Function: mgrcompat.run
        Name: pkg.mod_repo
      Result: true
     Comment: Module function pkg.mod_repo executed
     Started: 10:52:15.876124
    Duration: 2716.508
         SLS: channels
     Changed: ret:
                  deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_15.x bullseye main:
                      architectures: [
                          ]
                      comps:
                      - main
                      disabled: true
                      file: /etc/apt/sources.list
                      type: deb
                      uri: https://deb.nodesource.com/node_15.x
                      line: deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_15.x bullseye main
              
----------
          ID: disable_repo_1
    Function: mgrcompat.run
        Name: pkg.mod_repo
      Result: true
     Comment: Module function pkg.mod_repo executed
     Started: 10:52:18.592870
    Duration: 2523.471
         SLS: channels
     Changed: ret:
                  deb-src [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_15.x bullseye main:
                      architectures: [
                          ]
                      comps:
                      - main
                      disabled: true
                      file: /etc/apt/sources.list
                      type: deb-src
                      uri: https://deb.nodesource.com/node_15.x
                      line: deb-src [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_15.x bullseye main
```

If we apply the highstate one more time, the content of the external repo is concatenated in sources.list:

```
root@uyuni05v : /etc/apt # cat sources.list
deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_15.x bullseye maindeb-src [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_15.x bullseye maindeb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_15.x bullseye maindeb-src [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_15.x bullseye maindeb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_15.x bullseye maindeb-src [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_15.x bullseye mainroot@uyuni05v : /etc/apt #
```

Not sure about what exactly is being acheived here. Does Uyuni tries to disable the external repositories ? We don't want to the highstate to diable them.

### Steps to reproduce

1. Configure external repositories
2. Apply highstate
3. Check content og /etc/apt/sources.list

### Uyuni version

```bash
uyuni:~ # zypper info Uyuni-server-release
Loading repository data...
Reading installed packages...


Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2023.03-220400.199.1.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2023.03-220400.199.1.uyuni2.src
Summary        : Uyuni Server
Description    : 
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

**Comment by zzaimeche** [comment]
We believe we know why this happens, and would expect it to affect salt running on any debian distro, although we haven't confirmed that. I've pasted the comments from the engineering team below:

_"This is actually a bug in "python3-apt" package. The "aptsources" module (provided by python-apt package) is used by Salt "aptpkg" module and is currently messing with the "signed-by" repo option._

_The current code only accepts "arch" and "trust" options, any other option, even if valid ones is currently making "aptsources" to mess and consider this repo as invalid. Then party starts..._

_As mentioned, "signed-by" is a valid opts: https://manpages.ubuntu.com/manpages/focal/en/man5/sources.list.5.html_

_We see here the conflicting code still existing in upstream python-apt:
https://git.launchpad.net/python-apt/tree/aptsources/sourceslist.py?id=main#n360 "_

So, a duplicate entry is added to sources.list every time the repo is considered 'invalid', and the bug in python3-apt causes the repo to be considered invalid, because it does not recognise the 'signed-by' parameter. The final fix will be a change to python3-apt so that it can recognise that parameter. The bug is not specific to uyuni.

**Comment by guillomovitch** [comment]
There seem to be an upstream bug report already:
https://bugs.launchpad.net/ubuntu/+source/python-apt/+bug/1862764

Maybe someone with better understanding of the problem could add a note mentionning Uyuni case ?

**Comment by m-czernek** [comment]
Thank you for the bug report folks! As Zara pointed out, the problem is in the `python3-apt` package. Looking at the upstream response, it is not clear to me whether they want to fix the code or not--they seem to have migrated to a newer backend, but currently, I could reproduce the issue on ubuntu 18.04, 20.04, and 22.04.

Consequently, we decided to introduce a patch in our build, until the upstream fixes the issue. I have created the following submit requests in OBS, which is where we build Uyuni:

https://build.opensuse.org/request/show/1133389
https://build.opensuse.org/request/show/1133388
https://build.opensuse.org/request/show/1133391
https://build.opensuse.org/request/show/1133390
https://build.opensuse.org/request/show/1133393
https://build.opensuse.org/request/show/1133392

The fix should be available in the next minor release.
