### ISSUE TITLE
Rocky Linux 9 Status code: 403

### ISSUE THREAD

**Issue by nkane2898** [uyuni-project/uyuni#6820]
### Problem description

I am unable to update packages via dnf update or through the uyuni web interface. I can apply the highstate to the server successfully. Successfully applied state(s): highstate
 
It appears to be an issue with rhn/manager/download/rockylinux9-x86_64/repodata/repomd.xml 

If I curl the URL I see this on the client.

        <section id="spacewalk-content">
          You need a token to access /manager/download/rockylinux9-x86_64/repodata/repomd.xml
        </section>

### Steps to reproduce

1. sudo dnf update fails
2. System > Software > Upgrade in WebUI fails

### Uyuni version

```bash
Loading repository data...
Reading installed packages...


Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2023.03-220400.199.1.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2023.03-220400.199.1.uyuni2.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

### Useful logs

```bash
[user@ds-staging-isc ~]$ sudo dnf update
Updating Subscription Management repositories.
Unable to read consumer identity

This system is not registered with an entitlement server. You can use subscription-manager to register.

Rocky Linux 9 (x86_64)                                                                                   12 kB/s | 3.8 kB     00:00
Errors during downloading metadata for repository 'susemanager:rockylinux9-x86_64':
  - Status code: 403 for https://ds-uyuni.changed.com:443/rhn/manager/download/rockylinux9-x86_64/repodata/repomd.xml (IP: 172.26.31.71)
Error: Failed to download metadata for repo 'susemanager:rockylinux9-x86_64': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

----------
          ID: pkg_installed
    Function: pkg.installed
        Name: pkg_installed
      Result: false
     Comment: Error occurred installing package(s). Additional info follows:

errors:
    - Running scope as unit: run-r6a18f7efa11f42ada22f5746ff2fc908.scope
      Updating Subscription Management repositories.
      Unable to read consumer identity
      
      This system is not registered with an entitlement server. You can use subscription-manager to register.
      
      Rocky Linux 9 (x86_64)                           12 kB/s | 3.8 kB     00:00    
      Errors during downloading metadata for repository 'susemanager:rockylinux9-x86_64':
        - Status code: 403 for https://ds-uyuni.changed.com:443/rhn/manager/download/rockylinux9-x86_64/repodata/repomd.xml (IP: 172.26.31.71)
      Error: Failed to download metadata for repo 'susemanager:rockylinux9-x86_64': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
     Started: 19:53:17.657182
    Duration: 3625.845
         SLS: packages.pkginstall
     Changed: {}
```

**Comment by jratajczak81** [comment]
Hi
I spent 4 very long days to solve this problem on my servers. The problem starts when I upgraded server from AlmaLinux8 to AlmaLinux9 (leapp), but maybe informations will be useful in other cases. 
**First of all** - simple curl to repomd file from repo file will always return error because.... you need an access token :) 
Try this:
1) Get susemanager_token from repo file for specific repo
2) Send X-Mgr-Auth header with curl:
curl -H "X-Mgr-Auth: [susemanager_token_here]" -k <url_to_repomod.xml>
3) This should work
**Second** - configuration option susemanager_token defined in repo file for each repository is not known for yum/dnf - try yum update -d 10 and you will see "Unknown configuration option"
**Third** - this option (susemanager_token) is used by susemanagerplugin for dnf/yum (simple python script - search for susemanagerplugin.py file) - this plugin just get susemanager_token and send X-Mgr-Auth header

And what was the problem - simple think - after upgrade from Alma8 to Alma9 susemanagerplugin.py was in /usr/lib/python3.6/site-packages/dnf-plugins/ while it should be in /usr/lib/python3.9/site-packages/dnf-plugins/susemanagerplugin.py so it was... unavailable :)
Just create a symlink/copy/move to /usr/lib/python3.9/site-packages/dnf-plugins and it works :) 

I have no idea if your problem is the same, but you should check this  :)

**Comment by mcalmer** [comment]
You use the "traditional stack" which is not supported anymore in Uyuni.
We only support "salt".

**Comment by FooBarTrixibell** [comment]
I have connected all my systems via salt and can update them via the uyuni front end, I cannot however do `yum install BLAH` because I get a 403 error since updating (in order to get Alma9 repos). Does this mean that all yum/dnf actions can no longer be done with Uyuni? If so it will break all sorts of things, install scripts, ansible playbooks etc. It seems a strange decision. Is there any way just to remove the requirement for the susemanager_token in apache? My server is entirely internal so I really don't need to stop access to these repos.

If not I feel I may have to go back to the old locally hosted repositories using lftp to sync like a caveman!

**Comment by mcalmer** [comment]
Uyuni is made for systemsmanagement.  So the usecase is, that actions will be execueted from the centrally from the server.
When you register a system, it gets the channels defined on the sever and with it also the auth tokens needed to access them.

Doing changes on the client and changing repositories on client side is not really what uyuni is made for.

But if you want, you can disable token validation.
Set in rhn.conf `java.salt_check_download_tokens = 0`.

**Comment by FooBarTrixibell** [comment]
That works perfectly, so, just to double check my understanding, although the salt registration adds the susemanager repositories to the yum.repos.d folder and in this file adds a line for each repo with 

susemanager_token=eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MTM1MjgwMDMsImlhdCI6MTY4MTk5MjAwMywibmJmIjoxNjgxOTkxODgzLCJqdGkiOiJqZnlHa0tTZTY4azZzYGN4U0s7cWZ3Iiwib3JnIjoxLCJvbmx5Q2hhbm5lbHMiOlsiY2VudG9zNy11eXVuaS1jbGllbnQteDg2XzY0Il19.RmBwlZhirPk74DcLP_AQucKXYgRzxET9y3Lo72tlOFI

each of which is a different token, this is not meant to allow yum to access the repositories?

Is this .repo file left over from when the susemanagerplugin.py was supported or is it used somehow with the salt install/update process?

**Comment by avshiliaev** [comment]
Closing as stale and (most probably) invalid. Please feel free to reopen if needed

**Comment by stdevel** [comment]
> And what was the problem - simple thing - after upgrade from Alma8 to Alma9 susemanagerplugin.py was in /usr/lib/python3.6/site-packages/dnf-plugins/ while it should be in /usr/lib/python3.9/site-packages/dnf-plugins/susemanagerplugin.py so it was... unavailable :)
> Just create a symlink/copy/move to /usr/lib/python3.9/site-packages/dnf-plugins and it works :)

I can confirm that this issue can still occur and this just fixed the issue for me. Thanks a ton for sharing this! 👍🏻 🥇
