### ISSUE TITLE
While Bootstrapping the client machine getting error 

### ISSUE THREAD

**Issue by rakeshsujan** [uyuni-project/uyuni#7125]
# Question

_What do you want to know about Uyuni?_

## Version of Uyuni Server and Proxy (if used)

`zypper info Uyuni-Server-release` _and_ `zypper info Uyuni-Proxy-release` _(if used)_

**Comment by rakeshsujan** [comment]
While bootstrapping the client machine getting the below error.

![image](https://github.com/uyuni-project/uyuni/assets/50227412/b3160a05-0f22-4897-8367-35c7529f034a)

**Comment by sbluhm** [comment]
is the server `uyuni`reachable without a fqdn? The fqdn should have been set before installation.
What happens when you try to download the given url manually via curl/browser?
also did you run `mgr-create-bootstrap-repo` to generate this? the file should be in your webserver directory under pub/repositories/res/9/bootstrap

**Comment by sbluhm** [comment]
Does the domain resolution work properly? Can you ping the server from those clients? I can see that the above window is trying to access the hostname without fqdn like `https://uyuni:443/`instead of `https://uyuni.example.com:443/`

**Comment by rakeshsujan** [comment]
@sbluhm 

The server is not pinging from those client machines, and the Internal team is checking these issues.

Once it's a success I will revert back to this ticket.
