### ISSUE TITLE
Unbelivable fact: Country Serbia exists

### ISSUE THREAD

**Issue by bmanojlovic** [uyuni-project/uyuni#746]
after just maybe 13 years... in most setups we do not have this country called Serbia but hey we do have country called Yugoslavia!

``` shell
 Error output
 ┌────────────────────────────────────────────────────────────────────────────────
 │The answer 'RS' provided for 'Country code (Examples: "US", "JP", "IN", or type "?" to see a list)' is invalid.   
 │ERROR: spacewalk-setup failed
```

who manages to find Yugoslavia on (normal modern) map will have a free beer from me...
https://en.wikipedia.org/wiki/Serbia  <--- This DOES exist
https://en.wikipedia.org/wiki/Yugoslavia <---  This DOES NOT exist

Please it is really not fun after 10+ year i still can't find it in systems ... 
Yes i know it is not only Uyuni fault but it is not funny to live in Yugoslavia to be able to use software package from 2019...

Fun Fact: 20 years from bombing of Yugoslavia which looks you like to be reminded of...

**Comment by MuGrU** [comment]
Hello @cbbayburt 

I would like to contribute on this issue as my first open-source contribution ! =)
I just need to clarify which DB should I collect those data and if should be in the valid_countries.sql format.

The ISO-3166 country codes does not provide the entire data, only preview or [Country Codes Collection](https://www.iso.org/publication/PUB500001.html) paid service.

So I wrote a script to collect data from this [JSON](https://raw.githubusercontent.com/lukes/ISO-3166-Countries-with-Regional-Codes/master/all/all.json) and write in the format of valid_countries.sql:
Ex:
insert into valid_countries(code,short_name,name) values ('RS','Serbia','Southern Europe');

Does it work for you guys ? 
If not just let me know what you are expecting and I will be glad to help.

**Comment by bmanojlovic** [comment]
I have found another source of country info:
https://restcountries.eu/

```
curl https://restcountries.eu/rest/v2/name/Serbia|jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1033  100  1033    0     0   5270      0 --:--:-- --:--:-- --:--:--  5270
[
  {
    "name": "Serbia",
    "topLevelDomain": [
      ".rs"
    ],
    "alpha2Code": "RS",
    "alpha3Code": "SRB",
    "callingCodes": [
      "381"
    ],
    "capital": "Belgrade",
    "altSpellings": [
      "RS",
      "Srbija",
      "Republic of Serbia",
      "Република Србија",
      "Republika Srbija"
    ],
    "region": "Europe",
    "subregion": "Southern Europe",
    "population": 7076372,
    "latlng": [
      44,
      21
    ],
    "demonym": "Serbian",
    "area": 88361,
    "gini": 27.8,
    "timezones": [
      "UTC+01:00"
    ],
    "borders": [
      "BIH",
      "BGR",
      "HRV",
      "HUN",
      "KOS",
      "MKD",
      "MNE",
      "ROU"
    ],
    "nativeName": "Србија",
    "numericCode": "688",
    "currencies": [
      {
        "code": "RSD",
        "name": "Serbian dinar",
        "symbol": "дин."
      }
    ],
    "languages": [
      {
        "iso639_1": "sr",
        "iso639_2": "srp",
        "name": "Serbian",
        "nativeName": "српски језик"
      }
    ],
    "translations": {
      "de": "Serbien",
      "es": "Serbia",
      "fr": "Serbie",
      "ja": "セルビア",
      "it": "Serbia",
      "br": "Sérvia",
      "pt": "Sérvia",
      "nl": "Servië",
      "hr": "Srbija",
      "fa": "صربستان"
    },
    "flag": "https://restcountries.eu/data/srb.svg",
    "regionalBlocs": [
      {
        "acronym": "CEFTA",
        "name": "Central European Free Trade Agreement",
        "otherAcronyms": [],
        "otherNames": []
      }
    ],
    "cioc": "SRB"
  }

```

**Comment by cbbayburt** [comment]
> Hello @cbbayburt
> 
> I would like to contribute on this issue as my first open-source contribution ! =)
> I just need to clarify which DB should I collect those data and if should be in the valid_countries.sql format.
> 
> The ISO-3166 country codes does not provide the entire data, only preview or [Country Codes Collection](https://www.iso.org/publication/PUB500001.html) paid service.
> 
> So I wrote a script to collect data from this [JSON](https://raw.githubusercontent.com/lukes/ISO-3166-Countries-with-Regional-Codes/master/all/all.json) and write in the format of valid_countries.sql:
> Ex:
> insert into valid_countries(code,short_name,name) values ('RS','Serbia','Southern Europe');
> 
> Does it work for you guys ?
> If not just let me know what you are expecting and I will be glad to help.
> 
> Another alternatives DBs: maybe /usr/share/xml/iso-codes/iso_3166.xml
> https://gis.stackexchange.com/questions/1047/full-list-of-iso-alpha-2-and-iso-alpha-3-country-codes

Hi @MuGrU,

I'm glad you're interested in making a contribution!

The mapping from the ISO to our format should be as follows:

ISO | SQL
----|----
Full Name | name
Name | short_name
Alpha-2 code | code

Example:
```
insert into valid_countries(code, short_name, name) 
    values ('RS', 'Serbia', 'the Republic of Serbia');
```
Neither the JSON you linked, nor the one @bmanojlovic provided does include full names. I'd suggest you look up the missing full names either from https://www.iso.org/obp/ui/#home.

In the end, the PR shall remove outdated insert statements and add the missing ones into `valid_countries.sql`, preferably in alphabetical order by code.

Please note that this SQL file is *only* executed on a fresh Uyuni installation. So in addition to that, we'll need another SQL script for migration from older versions.

Migration scripts reside in `/schema/spacewalk/upgrade/` directory. The scripts here include I/U/D statements in order to put the table in the desired state from the older version. There shall be a separate file for each table which needs migration, with a filename such as: `XXX-tableName-feature.sql`. The number in the name determines the order of execution of these scripts, but in this case, only one file will be needed so you can pick any unique number.

Example: 
https://github.com/uyuni-project/uyuni/blob/master/schema/spacewalk/upgrade/susemanager-schema-4.0.10-to-susemanager-schema-4.0.11/001-add-minion-checkin-tasko-job.sql

**Comment by joesusecom** [comment]
I haven’t looked into the actual codebase, but I’d bet that we are already maintaining valid and current country mappings on the OS level in glibc locale or elsewhere. In that case, I’d rely on those, either at build time or even better in the running system, rather than importing data from external resources. Countries and borders change more frequently than one might think, and you don’t want to maintain this yourselves.

**Comment by mcalmer** [comment]
PRs were merged. Should be in the next Uyuni release

**Comment by bmanojlovic** [comment]
appreciated, thanks to everyone involved
