### ISSUE TITLE
Package Locking / Mass Package Locking

### ISSUE THREAD

**Issue by kurzandras** [uyuni-project/uyuni#7470]
# Question

Hello Guys! 

I would like to ask some questions which are really important for me regarding package locking on SLES12/15 clients: 

1: Is there a possibility to lock packages on multiple clients using the "System Set Manager"? I could find update,install,remove,verify options, but no lock is to be found there. The problem is that I have to lock a specific installed package with a specific version (i.e. cryptsetup-2.0.6-3.3.1.x86_64) on many hosts but I can not see the option for it anywhere.

2: If there is no such a feature could you please suggest a workaround how to lock a package with the given version on thousands of hosts quickly?

3: If I lock a specific package on a client using zypper (e.g. zypper al cryptsetup=2.0.6-3.3.1) the Uyuni UI does not display it as locked, it displays it as locked only if I use the UI for locking it. Why is that? Is this the expected behaviour?

4: If I lock a specific package on a client through the UI it will still be considered as upgradeable and Uyuni shows 1 upgrade available for that package. Can I somehow exclude this package from the list of upgradeable packages so that after fully patching a system it would report "System is up to date"?

5: My last question is if there are any other channels on which someone could ask questions, get support/trainings?

Thank you very much in advance!

## Version of Uyuni Server and Proxy (if used)

Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2023.04-220400.204.2.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2023.04-220400.204.2.uyuni2.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.

**Comment by dvosburg** [comment]
Currently to do this in bulk you can create a salt state to ensure the right info is appended to '/etc/zypp/locks'  file.  

1: Is there a possibility to lock packages on multiple clients using the "System Set Manager"? I could find update,install,remove,verify options, but no lock is to be found there. The problem is that I have to lock a specific installed package with a specific version (i.e. cryptsetup-2.0.6-3.3.1.x86_64) on many hosts but I can not see the option for it anywhere.

There is not a place to do this from the UI on bulk.  


2: If there is no such a feature could you please suggest a workaround how to lock a package with the given version on thousands of hosts quickly?

You could use the API call schedulePackageLockChange and script it to be applied to multiple systems, but that is not the same.

I would create a salt state to append your lock to '/etc/zypp/locks'  - and perhaps create a recurring schedule for it to prevent drift.  If you need help setting up such a state, let us know.



3: If I lock a specific package on a client using zypper (e.g. zypper al cryptsetup=2.0.6-3.3.1) the Uyuni UI does not display it as locked, it displays it as locked only if I use the UI for locking it. Why is that? Is this the expected behaviour?

It is expected behavior, but not really desired.  This is a feature request, for certain.



4: If I lock a specific package on a client through the UI it will still be considered as upgradeable and Uyuni shows 1 upgrade available for that package. Can I somehow exclude this package from the list of upgradeable packages so that after fully patching a system it would report "System is up to date"?

Not currently - request it!

5: My last question is if there are any other channels on which someone could ask questions, get support/trainings?

There may be more opppptions, but thanks for bringing it up here.

**Comment by dvosburg** [comment]
You may also wish to go here for more "discussion"

https://github.com/uyuni-project/uyuni/discussions

**Comment by kurzandras** [comment]
Thank you very much for your detailed answer!
