### ISSUE TITLE
Cant trust deb gpg key

### ISSUE THREAD

**Issue by sorquan** [uyuni-project/uyuni#7681]
### Problem description

Cant sync. Imported gpg with gpg --keyring /var/lib/spacewalkgpgdir --import /tmp/zabbix-official-repo.key

```
uyuni-mgr:/var/log/rhn/reposync # spacewalk-repo-sync -c ubuntu-2204-amd64-main-zabbix-6.0
20:27:02 ======================================
20:27:02 | Channel: ubuntu-2204-amd64-main-zabbix-6.0
20:27:02 ======================================
20:27:02 Sync of channel started.
20:27:02 Base URL: https://repo.zabbix.com/zabbix/6.0/ubuntu
20:27:02 Suite: jammy
20:27:02 Component: main
20:27:02 Channel architecture: amd64
20:27:04 Plugin error: GPG verification failed: https://repo.zabbix.com/zabbix/6.0/ubuntu/dists/jammy/InRelease
20:27:04 Total time: 0:00:01
[ERROR   ] Repo has no valid GPG signature. Raising GeneralRepoException.

```

### Steps to reproduce

1. Add repo
2. Add channel
3. gpg --keyring /var/lib/spacewalkgpgdir --import /tmp/zabbix-official-repo.key
4. spacewalk-repo-sync -c ubuntu-2204-amd64-main-zabbix-6.0

### Uyuni version

```bash
2023.04
```

**Comment by ppanon2022** [comment]
Have you tried putting the URL for the key in the Security:GPG section of the channel details?
GPG key URL: https://repo.zabbix.com/zabbix-official-repo.key

The thing is that the key file appears to contain two sub-keys, and it's not clear at first which is being used to sign.
```
gpg zabbix-official-repo.key
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
pub   dsa1024 2012-10-28 [SC]
      FBABD5FB20255ECAB22EE194D13D58E479EA5ED4
uid           Zabbix SIA <packager@zabbix.com>
sub   elg1024 2012-10-28 [E]
pub   rsa2048 2016-07-15 [SC]
      A1848F5352D022B9471D83D0082AB56BA14FE591
uid           Zabbix LLC <packager@zabbix.com>
sub   rsa2048 2016-07-15 [E]
```

but if you try to verify the InRelease file it appears to be using the RSA key
```
gpg --verify InRelease
gpg: Signature made Mon Sep 25 03:39:18 2023 PDT
gpg:                using RSA key A1848F5352D022B9471D83D0082AB56BA14FE591
gpg: Can't check signature: No public key
```

So try using the following for the remaining Security:GPG fields:
GPG key ID: A14FE591
GPG key Fingerprint: A1848F5352D022B9471D83D0082AB56BA14FE591

This may have been more suitable as a discussion than as an issue, although I had some similar problems because the documentation isn't very clear on this.

**Comment by sorquan** [comment]
And now i don't understand how trust GPG key on manager server for rpm repository

Receiving this when start syncing:
`uyuni-mgr # spacewalk-repo-sync -c centos7-x86_64-zabbix-6.0
18:34:54 ======================================
18:34:54 | Channel: centos7-x86_64-zabbix-6.0
18:34:54 ======================================
18:34:54 Sync of channel started.
Warning: File 'repomd.xml' from repository 'centos7-x86_64-zabbix-6.0' is unsigned.

    Note: Signing data enables the recipient to verify that no modifications occurred after the data
    were signed. Accepting data with no, wrong or unknown signature can lead to a corrupted system
    and in extreme cases even to a system compromise.

    Note: File 'repomd.xml' is the repositories master index file. It ensures the integrity of the
    whole repo.

    Warning: We can't verify that no one meddled with this file, so it might not be trustworthy
    anymore! You should not continue unless you know it's safe.

File 'repomd.xml' from repository 'centos7-x86_64-zabbix-6.0' is unsigned, continue? [yes/no] (no):`

**Comment by mcalmer** [comment]
Well, that repo is not signed. But afaik you set the checkbox "Has signed Metadata" in the repository configuration.
If you say "it is signed" but the repo is not signed, you get this error.

**Comment by sorquan** [comment]
> Well, that repo is not signed. But afaik you set the checkbox "Has signed Metadata" in the repository configuration. If you say "it is signed" but the repo is not signed, you get this error.

Thanks!

**Comment by ppanon2022** [comment]
> Well, that repo is not signed. But afaik you set the checkbox "Has signed Metadata" in the repository configuration. If you say "it is signed" but the repo is not signed, you get this error.

While that may be what the error message seems to indicate at first glance, there are in fact InRelease and Release.gpg files, and they do appear to contain a signature

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Origin: Zabbix
Label: zabbix
Suite: jammy
Codename: jammy
Version: 22.04
Date: Mon, 25 Sep 2023 10:39:18 UTC
Architectures: amd64
Components: main non-free contrib
Description: Zabbix official apt repository
.
.
.
-----BEGIN PGP SIGNATURE-----

iQEzBAEBCgAdFiEEoYSPU1LQIrlHHYPQCCq1a6FP5ZEFAmURY1YACgkQCCq1a6FP
5ZGZDQf9Fa9rfPVmcOOpxUqdUrwO102cYza4ERAwi9Ypcb8ZxesokfRAjfSMvg9h
sDOHVubtfr4BnjHlZeWesFHzFaMR/deu2lFRqSy7UPNjwwMpLXba4N/adRqJgJ+Q
GOxDJnJ3S2IuBtzX28rLTnqPtHot8lB+nR5M8XuhTv02VyX4viB8EcaoEm3zFQgi
lXc7YLYAIgk7bHOo1zw8ozOGp3+9rUlD0fZQUTm/70W7PGTYbov6Zki9JSNYW0n1
/Fdk+y/X43olpOlgWXtn2PM4DdV0j3x6+khC+Zb7rJbsDgZfBQf8GGzvWiFTa1eP
orSNeBUlch+xCcgBBzzz6YdchK36ag==
=1bV4
-----END PGP SIGNATURE-----
```
Trying to manually verify that file indicates that the problem (as I indicated in my other post) is that the key can't be found, because the import is likely only importing or indexing the first DSA key in a key file with subkeys instead of the second needed RSA key. Disabling the metadata check needlessly reduces security and exposes the user to possible injection of compromised packages.
