### ISSUE TITLE
Is is possible to deploy specific stable version of Uyuni server? 

### ISSUE THREAD

**Issue by szymonsypula** [uyuni-project/uyuni#7693]
Hello 

Is it possible to deploy specific version of Uyuni rather than going with latest released one as per rolling-release lifecycle? 
It would be beneficial to be able to deploy specific version due if minor infrastructure requirements change from version to version breaks existing deployment pipeline. 

Example infra requirements are base os for specific version or certificate schema validation. 

Remarks. 
I am not using sumaform for Uyuni deployment but custom deployment pipeline. 

Best regards
Szymon

**Comment by stdevel** [comment]
Hi @szymonsypula,
using older versions is possible, but not supported. But I do the same to version-pin my environments.

There are snapshot repositories that you can use instead of the latest repositories - I documented them here: https://github.com/uyuni-project/uyuni-docs/issues/2530
I'm working on a PR to have this included in the documentation.

**Comment by szymonsypula** [comment]
Thank you, closing ticket.
